### ISSUE TITLE
Argument order swapped

### ISSUE THREAD

**Issue by rektide** [xetorthio/etcd-fs#12]
Mount commands typically expect arguments in "what to mount" "where to mount" order. Presently etcd-fs flips this, expecting where to mount, then what to mount.

This is particularly troublesome if trying to use automounters, for example systemd. The automounter will be unable to understand that http://localhost:4001/ is not a local directory where the FS should mount.

**Comment by artheus** [comment]
@xetorthio Is there a specific reason for this being swapped?

**Comment by xetorthio** [comment]
No. There is no reason. I guess we could do it right :)

**Comment by artheus** [comment]
I will then look into making a pr for this change

**Comment by artheus** [comment]
Please review #13

**Comment by artheus** [comment]
This can now be closed, as #13 is merged.
